contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/deniscerri/ytdlnis/issues/new/choose
    about: Issues and requests about the app itself should be opened in the ytdlnis repository instead
  - name: 🖥️ YTDLnis website
    url: https://ytdlnis.org/help/
    about: Guides, troubleshooting, and answers to common questions
